(require 'helm-config)
(require 'helm-ag)
;(require 'helm-descbinds)

;(helm-descbinds-mode)
(helm-mode 1)
(add-to-list 'helm-completing-read-handlers-alist '(find-file . nil))
(global-set-key (kbd "C-c h") 'helm-mini)
(global-set-key (kbd "C-c b") 'helm-descbinds)
(global-set-key (kbd "C-c o") 'helm-occur)
(global-set-key (kbd "C-c C-a") 'helm-ag)
(global-set-key (kbd "C-x C-f") 'helm-find-files)
(global-set-key (kbd "C-x C-r") 'helm-recentf)
(global-set-key (kbd "C-c C-p") 'helm-projectile)
